### ISSUE TITLE
Please add a license.

### ISSUE THREAD

**Issue by samuelh2005** [Mangolise/mango-anti-cheat#1]
Without a license we won't be legally allowed to use your library.

Since you have put this on Github, you have accpeted the Github Terms of Service, which only allows us to view and fork your library (and nothing more). (see https://choosealicense.com/no-permission/ for more information).

https://choosealicense.com/licenses/ is a list of common licenses you can choose from. I recommend the [MIT License](https://choosealicense.com/licenses/mit/), but the choice is yours.

**Comment by CoPokBl** [comment]
@ajh123 sorry about that oversight. We have chosen the MIT license in line with our other open source projects. The file has been added to the project now.
