### ISSUE TITLE
please use computeIfAbsent

### ISSUE THREAD

**Issue by MelonHell** [Mangolise/mango-anti-cheat#2]
https://www.baeldung.com/java-map-computeifabsent

you make too many unnecessary calls to maps

**Comment by CoPokBl** [comment]
Thanks for your feedback. I have changed the checks to use computeIfAbsent instead of manually checking for their absence in [cfbea21](https://github.com/Mangolise/mango-anti-cheat/commit/cfbea2181341ccbc7111ba6088c53284aebe5ca7).

**Comment by MelonHell** [comment]
https://github.com/Mangolise/mango-anti-cheat/commit/cfbea2181341ccbc7111ba6088c53284aebe5ca7#r146662459

**Comment by CoPokBl** [comment]
Another valid point, fixed in https://github.com/Mangolise/mango-anti-cheat/commit/f7102d84960dfb521fed2dffff94c4ca3c6f0131
